/*#389 easy
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class FindTheDifference {
	public char findTheDifference(String s, String t) {
		int len1 = s.length(), len2 = t.length();
        int[] table = new int[26];
        	for(int i = 0;i < len1;i++)
        		table[s.charAt(i) - 'a']++;
        	
        	for(int i = 0;i < len2;i++) {
        		table[t.charAt(i) - 'a']--;
        		if(table[t.charAt(i) - 'a'] == -1)
        			return t.charAt(i);
        	}
        	
        	return 'a';
    }
	//using bit manipulation
	public char findTheDifference2(String s, String t) {
		int len1 = s.length(), len2 = t.length();
        char ch = 0;
        	for(int i = 0;i < len1;i++)
        		ch ^= s.charAt(i);
        	
        	for(int i = 0;i < len2;i++) {
        		ch ^= t.charAt(i);
        	}
        	
        	return ch;
    }
}
